node_engine/NetManager/README.md
node_engine/NetManager/env/EnvironmentManager.go
node_engine/NetManager/env/serviceTranslationTable.go
node_engine/NetManager/proxy/ProxyTunnel.go
node_engine/NetManager/proxy/Proxy_test.go
node_engine/NetManager/proxy/hostCache.go
node_engine/NetManager/proxy/proxyCache.go
node_engine/NetManager/testEnvironment/TwoNetnsDev1.go
node_engine/NetManager/testEnvironment/TwoNetnsDev2.go

- Added basic implementation of the proxy resolution table 
- Added round robin proxy scheme 
- Updated test examples 
- Updated proxy tests 
- closes #1

 Proxy table - closes #1

---

cluster_orchestrator/cluster-scheduler/requirements.txt
root_orchestrator/cloud-scheduler/requirements.txt
root_orchestrator/docker-compose.yml

closes #14 
Fixed celery dependency

Fix scheduler celery requirements - closes #14

---

cluster_orchestrator/cluster-manager/cluster_balancer.py
cluster_orchestrator/cluster-manager/cluster_manager.py
cluster_orchestrator/cluster-manager/system_manager_requests.py
cluster_orchestrator/cluster-scheduler/mongodb_client.py
node_engine/NetManager/NetManager.go
node_engine/NetManager/config/tuncfg.json
node_engine/NetManager/env/Env_test.go
node_engine/NetManager/env/EnvironmentManager.go
node_engine/NetManager/env/netUtils.go
node_engine/NetManager/env/serviceTranslationTable.go
node_engine/NetManager/env/tableQueryRequests.go
node_engine/NetManager/proxy/ProxyTunnel.go
node_engine/dockerclient.py
node_engine/mqtt_client.py
node_engine/net_manager_requests.py
node_engine/start-up.sh

Added implementation of the Node table query and updated container deployment
- A container deployment must contain all the information for an initial local table resolution of that container
- The deployment rn works only for the first instance of a service. This must be updated once the scaling up and down feature is implemented
closes #3

3 node manager table query resolution

---

node_engine/NetManager/docs/network/architecture.md
node_engine/README.md
root_orchestrator/system-manager-python/README.md

Updated docs

---

node_engine/NetManager/proxy/ProxyTunnel.go

Added UDP support

---

README.md
cluster_orchestrator/README.md
cluster_orchestrator/docker-compose.yml

Parametric cluster dockerfile closes #31

---

cluster_orchestrator/cluster-manager/mongodb_client.py
cluster_orchestrator/cluster-scheduler/calculation.py
cluster_orchestrator/docker-compose-amd64.yml
cluster_orchestrator/docker-compose-arm.yml
root_orchestrator/system-manager-python/services/application_management.py

Fix active rescheduling

---

.github/workflows/cluster_manager_develop_image.yml
.github/workflows/cluster_scheduler_develop_image.yml
.github/workflows/node_engine_develop_artifacts.yml
.github/workflows/root_scheduler_develop_image.yml
.github/workflows/root_system_manager_develop_image.yml

136 develop image build

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/proposal.md

added issues template

---

cluster_orchestrator/docker-compose-amd64.yml
cluster_orchestrator/docker-compose-arm.yml
root_orchestrator/docker-compose-amd64.yml
root_orchestrator/docker-compose-arm.yml
root_orchestrator/system-manager-python/ext_requests/apps_db.py
root_orchestrator/system-manager-python/ext_requests/cluster_db.py

191 add historical usage data

---

.github/workflows/cluster_manager_image.yml
.github/workflows/cluster_scheduler_image.yml
.github/workflows/root_scheduler_image.yml
.github/workflows/root_system_manager_image.yml
root_orchestrator/system-manager-python/ext_requests/apps_db.py

201 packages alpha releases as latest

---

go_node_engine/model/Node.go
go_node_engine/model/gpu/nvsmi_bindings.go

Fixes #236 Tot GPU memory consumption Issue

fixed GPU tot free memory calculation

---

README.md

Issue: https://github.com/oakestra/oakestra/issues/228
For detailed information please have a look at the linked ticket.
Feel free to check out the branch locally to verify that the final README looks as expected or
what is even easier, you can inspect the markdown changes directly in the GUI:

Increase comprehension & readability of the README

---

go_node_engine/go.mod
go_node_engine/go.sum
go_node_engine/virtualization/ContainersManagement.go

216 node is not reporting metrics correctly

---

.github/workflows/root_system_manager_tests.yml
cluster_orchestrator/cluster-manager/mongodb_client.py

246 problem during the aggregation of the data skipping the node

---

.github/workflows/cluster_manager_image.yml
.github/workflows/cluster_scheduler_image.yml
.github/workflows/root_scheduler_image.yml
.github/workflows/root_system_manager_image.yml

Updated cosign version

---

cluster_orchestrator/cluster-scheduler/calculation.py

Added extract specs default

---

cluster_orchestrator/cluster-manager/mongodb_client.py
go_node_engine/model/Service.go
go_node_engine/virtualization/ContainersManagement.go
root_orchestrator/system-manager-python/ext_requests/apps_db.py

223 application logs

---

.github/workflows/root_resource_abstractor_image.yml
root_orchestrator/docker-compose.yml
root_orchestrator/resource-abstractor/api/v1/resources_blueprint.py
run-a-cluster/1-DOC.yaml
run-a-cluster/override-alpha-versions.yaml

268 missing resource abstractor from 1 doc

---

cluster_orchestrator/cluster-manager/cluster_manager.py
root_orchestrator/system-manager-python/ext_requests/cluster_requests.py
root_orchestrator/system-manager-python/system_manager.py
run-a-cluster/1-DOC.yaml
run-a-cluster/override-alpha-versions-v301.yaml

Fixed ipv6 family on server sockets

256 allow management traffic to use ipv6

---

cluster_orchestrator/override-custom-service-manager-version.yml
root_orchestrator/override-custom-service-manager-version.yml
root_orchestrator/resource-abstractor/api/v1/resources_blueprint.py

Unikernel scheduling resource calculation is broken

---

go_node_engine/build/build.sh
run-a-cluster/cluster-orchestrator.yml
run-a-cluster/root-orchestrator.yml
scripts/InstallOakestraWorker.sh
scripts/StartOakestraCluster.sh
scripts/StartOakestraFull.sh
scripts/StartOakestraRoot.sh

updated build scripts

---

root_orchestrator/resource-abstractor/db/apps_db.py
root_orchestrator/system-manager-python/blueprints/applications_blueprints.py
root_orchestrator/system-manager-python/system_manager.py

Fixing resources abstractor bugs

---

libraries/.gitignore
libraries/resource_abstractor_client/resource_abstractor_client/cluster_operations.py
root_orchestrator/resource-abstractor/db/clusters_db.py
root_orchestrator/system-manager-python/.gitignore
root_orchestrator/system-manager-python/blueprints/services_blueprints.py
root_orchestrator/system-manager-python/services/cluster_management.py

Services Id issue in frontend

---

root_orchestrator/resource-abstractor/api/v1/jobs_blueprint.py
root_orchestrator/resource-abstractor/db/jobs_db.py

instance number is an int

---

cluster_orchestrator/cluster-manager/requirements.txt
cluster_orchestrator/cluster-scheduler/requirements.txt
root_orchestrator/cloud-scheduler/requirements.txt
root_orchestrator/system-manager-python/requirements.txt

Fixes the custom library dependencies by pointing to "develop" instead of the legacy/merged feature branch

Fix custom library dependencies

---

cluster_orchestrator/cluster-scheduler/calculation.py
root_orchestrator/cloud-scheduler/calculation.py
root_orchestrator/cloud-scheduler/cloud_scheduler.py
root_orchestrator/system-manager-python/sla/schema.py
root_orchestrator/system-manager-python/sla/sla_documentation.md

Add a new constraint to allow specifying/restricting services to be deployed only on a specific set of clusters.
Why is this necessary:
This adds more flexibility and is a simple addition to the existing scheduling logic.
Concretely I need it to allow hierarchical FLOps, i.e. deploying learners for a specific cluster aggregator. I want to be sure that these learners are deployed on the same cluster as the cluster aggregator, plus I want to deploy one cluster aggregator per cluster. 
AFAIK we do not have any similar logic in place yet - the closest to it is to specify the node IP, which is too fine-grained for my use-case.
Here is a SLA you can use to test this out yourself:
```yaml
{
"sla_version": "v2.0",
"customerID": "Admin",
"applications": [
{
"applicationID": "",
"application_name": …
```

Add new clusters constraint

---

.github/workflows/stale-issue.yml

added stale issues bot
